# Generated by Django 3.0.8 on 2020-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hash_tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
